# -*- coding: utf-8 -*-
"""DL_LAB03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VEh7TcXkCWRPm7g9i1iF9U5tWkNuY24F
"""

import tensorflow as tf
from tensorflow.keras import datasets, models, layers, utils, regularizers
import matplotlib.pyplot as plt

# Load MNIST
(X_train, y_train), (X_test, y_test) = datasets.mnist.load_data()

# Normalize
X_train = X_train / 255.0
X_test = X_test / 255.0

# Take 4000 samples to observe overfitting
X_train = X_train[:2000]
y_train = y_train[:2000]

print("Data loaded and preprocessed successfully.")

#Baseline Model (Overfitting)
model = models.Sequential([
    layers.Input(shape=(28,28)),
    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.Dense(256, activation='relu'),
    layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=60, batch_size=64, validation_split=0.2, verbose=1)

# Plotting
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train')
plt.plot(history.history['val_accuracy'], label='Val')
plt.title('Overfitting Analysis : Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train')
plt.plot(history.history['val_loss'], label='Val')
plt.title('Overfitting Analysis : Loss')
plt.legend()
plt.show()

print("Baseline Test Evaluation:", model.evaluate(X_test, y_test, verbose=0))

#Batch Normalization Model
model_bn = models.Sequential([
    layers.Input(shape=(28, 28)),
    layers.Flatten(),
    layers.Dense(512),
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.Dense(256),
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.Dense(128),
    layers.BatchNormalization(),
    layers.Activation('relu'),
    layers.Dense(10, activation='softmax')
])

model_bn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_bn = model_bn.fit(X_train, y_train, epochs=60, batch_size=64, validation_split=0.2, verbose=1)

# Plotting
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_bn.history['accuracy'], label='Train')
plt.plot(history_bn.history['val_accuracy'], label='Val')
plt.title('Batch Norm Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_bn.history['loss'], label='Train')
plt.plot(history_bn.history['val_loss'], label='Val')
plt.title('Batch Norm Loss')
plt.legend()
plt.show()

print("Batch Norm Test Evaluation:", model_bn.evaluate(X_test, y_test, verbose=0))

model_bn.evaluate(X_test,y_test)

# L2 Regularization Model
model_l2 = models.Sequential([
    layers.Input(shape=(28,28)),
    layers.Flatten(),
    layers.Dense(512, activation='relu', kernel_regularizer=regularizers.l2(0.001)),
    layers.Dense(512, activation='relu', kernel_regularizer=regularizers.l2(0.001)),
    layers.Dense(512, activation='relu', kernel_regularizer=regularizers.l2(0.001)),
    layers.Dense(10, activation='softmax')
])

model_l2.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_l2 = model_l2.fit(X_train, y_train, epochs=60, batch_size=64, validation_split=0.2, verbose=1)

# Plotting
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_l2.history['accuracy'], label='Train')
plt.plot(history_l2.history['val_accuracy'], label='Val')
plt.title('L2 Regularization Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_l2.history['loss'], label='Train')
plt.plot(history_l2.history['val_loss'], label='Val')
plt.title('L2 Regularization Loss')
plt.legend()
plt.show()

print("L2 Test Evaluation:", model_l2.evaluate(X_test, y_test, verbose=0))

model_l2.evaluate(X_test,y_test)

#Dropout Model
model_dropout = models.Sequential([
    layers.Input(shape=(28,28)),
    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(10, activation='softmax')
])

model_dropout.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_dropout = model_dropout.fit(X_train, y_train, epochs=60, batch_size=64, validation_split=0.2, verbose=1)

# Plotting
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(history_dropout.history['accuracy'], label='Train')
plt.plot(history_dropout.history['val_accuracy'], label='Val')
plt.title('Dropout Accuracy')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_dropout.history['loss'], label='Train')
plt.plot(history_dropout.history['val_loss'], label='Val')
plt.title('Dropout Loss')
plt.legend()
plt.show()

print("Dropout Test Evaluation:", model_dropout.evaluate(X_test, y_test, verbose=0))

model_dropout.evaluate(X_test,y_test)