# -*- coding: utf-8 -*-
"""DL_Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujzE5QxWWuLYyBc105Od6eHSBogXwPuY
"""

import tensorflow as tf #DL library
from tensorflow.keras.models import Sequential #stack layers one after another
from tensorflow.keras.layers import Dense,Input #fully connected layer
import numpy as np #create sample data

X = np.random.randn(100,5)
y = np.random.randint(0,100)

model = Sequential()
model.add(Dense(1, activation='relu',input_shape=(1,)))

for i in range(8):
   model.add(Dense(1, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X,y,epochs=10,batch_size=1)

model.summary()

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import SGD, Adam
import matplotlib.pyplot as plt

# -----------------------------
# 1. DATA: 100 samples, 5 features
# -----------------------------
np.random.seed(42)
X = np.random.randn(100, 5)
y_binary = np.random.randint(0, 2, size=(100,1))  # for vanishing gradient
y_reg = np.random.rand(100,1)                     # for exploding gradient

# -----------------------------
# VANISHING GRADIENT DEMO
# -----------------------------
vg_model = Sequential()
vg_model.add(Input(shape=(5,)))

# 8 hidden layers with sigmoid to cause vanishing gradient
for _ in range(8):
    vg_model.add(Dense(64, activation='sigmoid'))

vg_model.add(Dense(1, activation='sigmoid'))

vg_model.compile(optimizer=SGD(learning_rate=0.1),
                 loss='binary_crossentropy',
                 metrics=['accuracy'])

print("=== VANISHING GRADIENT MODEL SUMMARY ===")
vg_model.summary()

# Train briefly
vg_model.fit(X, y_binary, epochs=20, batch_size=32, verbose=0)

# Compute gradients
with tf.GradientTape() as tape:
    predictions = vg_model(X, training=True)
    loss = tf.reduce_mean(tf.keras.losses.binary_crossentropy(y_binary, predictions))

gradients = tape.gradient(loss, vg_model.trainable_weights)
vg_grad_magnitudes = [tf.reduce_mean(tf.abs(g)).numpy() for g in gradients[::2]]  # weights only
vg_layer_idx = list(range(1, len(vg_grad_magnitudes)+1))

# Plot vanishing gradient
plt.figure(figsize=(7,4))
plt.plot(vg_layer_idx, vg_grad_magnitudes, marker='o', linestyle='-', color='purple')
plt.yscale('log')
plt.xlabel("Layer Index (Input → Output)")
plt.ylabel("Mean Gradient Magnitude")
plt.title("Vanishing Gradient Demo")
plt.grid(True)
plt.show()


# Compute gradients
with tf.GradientTape() as tape:
    predictions = eg_model(X, training=True)
    loss = tf.reduce_mean(tf.keras.losses.MSE(y_reg, predictions))

gradients = tape.gradient(loss, eg_model.trainable_weights)
eg_grad_magnitudes = [tf.reduce_mean(tf.abs(g)).numpy() for g in gradients[::2]]
eg_layer_idx = list(range(1, len(eg_grad_magnitudes)+1))