# -*- coding: utf-8 -*-
"""DL_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17SYUkOQ54EIVO7MezWvyqNr7JuCSnnNg
"""

import numpy as np
import matplotlib.pyplot as plt

# 2. Define the number of data points
n_samples = 100

# 3. Generate an array of x values
X = np.linspace(0, 10, n_samples)

# 4. Define the true slope (m_true) and intercept (b_true)
m_true = 2
b_true = 1

# 5. Generate y values with noise
noise = np.random.normal(0, 2, n_samples)  # Mean 0, std dev 2
y = m_true * X + b_true + noise

# 6. Create a scatter plot of the generated X and y values
plt.figure(figsize=(8, 6))
plt.scatter(X, y, label='Simulated Data', alpha=0.7)

# 7. Add labels to the x and y axes and a title to the plot
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Simulated Linear Regression Data')
plt.legend()

# 8. Display the plot
plt.grid(True)
plt.show()

print("Synthetic linear regression data generated and plotted.")
print(f"X shape: {X.shape}, y shape: {y.shape}")



import numpy as np

# 1. Define a function predict(X, m, b)
def predict(X, m, b):
    """Predicts y values given X, slope m, and intercept b."""
    return m * X + b

# 2. Define a function mse_loss(y_true, y_pred)
def mse_loss(y_true, y_pred):
    """Calculates the Mean Squared Error (MSE)."""
    return np.mean((y_true - y_pred)**2)

# 3. Define a function compute_gradients(X, y_true, y_pred)
def compute_gradients(X, y_true, y_pred):
    """Computes gradients of MSE loss with respect to m and b."""
    n = len(X)
    dm = (-2/n) * np.sum(X * (y_true - y_pred))
    db = (-2/n) * np.sum(y_true - y_pred)
    return dm, db

# 4. Implement the gradient_descent(X, y, learning_rate, n_iterations) function
def gradient_descent(X, y, learning_rate, n_iterations):
    """Implements Batch Gradient Descent."""
    m = 0.0 # Initialize slope
    b = 0.0 # Initialize intercept
    loss_history = []

    for i in range(n_iterations):
        y_pred = predict(X, m, b)
        loss = mse_loss(y, y_pred)
        loss_history.append(loss)

        dm, db = compute_gradients(X, y, y_pred)

        m -= learning_rate * dm
        b -= learning_rate * db

    return m, b, loss_history

# 5. Implement the stochastic_gradient_descent(X, y, learning_rate, n_epochs) function
def stochastic_gradient_descent(X, y, learning_rate, n_epochs):
    """Implements Stochastic Gradient Descent."""
    m = 0.0 # Initialize slope
    b = 0.0 # Initialize intercept
    loss_history = []
    n_samples = len(X)

    for epoch in range(n_epochs):
        # Shuffle indices for each epoch
        indices = np.arange(n_samples)
        np.random.shuffle(indices)

        for i in indices:
            x_i = X[i]
            y_i = y[i]

            y_pred_i = predict(x_i, m, b)
            dm, db = compute_gradients(np.array([x_i]), np.array([y_i]), np.array([y_pred_i]))

            m -= learning_rate * dm
            b -= learning_rate * db

        # Calculate loss over the entire dataset after each epoch
        y_pred_full = predict(X, m, b)
        loss_history.append(mse_loss(y, y_pred_full))

    return m, b, loss_history

# 6. Implement the mini_batch_gradient_descent(X, y, learning_rate, n_epochs, batch_size) function
def mini_batch_gradient_descent(X, y, learning_rate, n_epochs, batch_size):
    """Implements Mini-Batch Gradient Descent."""
    m = 0.0 # Initialize slope
    b = 0.0 # Initialize intercept
    loss_history = []
    n_samples = len(X)

    for epoch in range(n_epochs):
        # Shuffle indices for each epoch
        indices = np.arange(n_samples)
        np.random.shuffle(indices)

        for i in range(0, n_samples, batch_size):
            batch_indices = indices[i:i + batch_size]
            X_batch = X[batch_indices]
            y_batch = y[batch_indices]

            y_pred_batch = predict(X_batch, m, b)
            dm, db = compute_gradients(X_batch, y_batch, y_pred_batch)

            m -= learning_rate * dm
            b -= learning_rate * db

        # Calculate loss over the entire dataset after each epoch
        y_pred_full = predict(X, m, b)
        loss_history.append(mse_loss(y, y_pred_full))

    return m, b, loss_history

print("Optimizer functions (predict, mse_loss, compute_gradients, gradient_descent, stochastic_gradient_descent, mini_batch_gradient_descent) have been defined.")

import numpy as np

# 1. Define common parameters for the simulation
learning_rate = 0.01
n_iterations_gd = 1000 # For Gradient Descent
n_epochs_sgd_mbgd = 50 # For SGD and Mini-Batch GD
batch_size = 10 # For Mini-Batch GD

print(f"Simulation Parameters:\nLearning Rate: {learning_rate}\nGD Iterations: {n_iterations_gd}\nSGD/MBGD Epochs: {n_epochs_sgd_mbgd}\nMini-Batch Size: {batch_size}\n")

# 2. Run Gradient Descent
print("Running Gradient Descent...")
m_gd, b_gd, loss_history_gd = gradient_descent(X, y, learning_rate, n_iterations_gd)
print(f"GD - Final m: {m_gd:.4f}, Final b: {b_gd:.4f}, Final Loss: {loss_history_gd[-1]:.4f}")

# 3. Run Stochastic Gradient Descent
print("\nRunning Stochastic Gradient Descent...")
m_sgd, b_sgd, loss_history_sgd = stochastic_gradient_descent(X, y, learning_rate, n_epochs_sgd_mbgd)
print(f"SGD - Final m: {m_sgd:.4f}, Final b: {b_sgd:.4f}, Final Loss: {loss_history_sgd[-1]:.4f}")

# 4. Run Mini-Batch Gradient Descent
print("\nRunning Mini-Batch Gradient Descent...")
m_mbgd, b_mbgd, loss_history_mbgd = mini_batch_gradient_descent(X, y, learning_rate, n_epochs_sgd_mbgd, batch_size)
print(f"MBGD - Final m: {m_mbgd:.4f}, Final b: {b_mbgd:.4f}, Final Loss: {loss_history_mbgd[-1]:.4f}")

print("\nAll optimizers have been executed and their results stored.")

import matplotlib.pyplot as plt

# 1. Create a plot to compare the loss histories
plt.figure(figsize=(10, 7))

# Plot Gradient Descent loss history
plt.plot(range(len(loss_history_gd)), loss_history_gd, label='Gradient Descent', color='blue')

# Plot Stochastic Gradient Descent loss history
# Note: SGD loss history often represents loss per epoch, not per individual update.
plt.plot(range(len(loss_history_sgd)), loss_history_sgd, label='Stochastic Gradient Descent', color='red')

# Plot Mini-Batch Gradient Descent loss history
plt.plot(range(len(loss_history_mbgd)), loss_history_mbgd, label='Mini-Batch Gradient Descent', color='green')

# Add labels and title
plt.xlabel('Iterations (GD) / Epochs (SGD, MBGD)')
plt.ylabel('Mean Squared Error (MSE) Loss')
plt.title('Comparison of Optimizer Convergence')
plt.legend()
plt.grid(True)
plt.show()

print("Convergence plots for Gradient Descent, SGD, and Mini-Batch Gradient Descent have been generated.")